name: Monstrorvm
version: '1.0.0'
api-version: '1.16'
main: com.github.steeldev.monstrorvm.Monstrorvm
description: A plugin that allows users to create custom items and mobs!
author: Steel_Dev
commands:
  monstrorvmreload:
    description: Reload the configuration.
    aliases: mvreload
    permission: monstrorvm.admin
    permission-message: You dont have permission to use this command.
  spawnmonstrorvmmob:
    description: Spawn the specified custom mob.
    aliases: spawnmvmob
    permission: monstrorvm.admin
    permission-message: You dont have permission to use this command.
  killallmonstrorvmmobs:
    description: Kills all spawned custom mobs.
    aliases: killallmvmobs
    permission: monstrorvm.admin
    permission-message: You dont have permission to use this command.
  givemonstrorvmitem:
    description: Give yourself the specified custom item.
    aliases: givemvitem
    permission: monstrorvm.admin
    permission-message: You dont have permission to use this command.
  listmonstrorvmitems:
    description: Open a GUI that displays all registered custom items. Clicking one will give it to you.
    aliases: listmvitems
    permission: monstrorvm.admin
    permission-message: You dont have permission to use this command.
permissions:
  monstrorvm.admin:
    description: Allows the user administrator permissions for Monstrorvm.
    default: op
